In [0]:
import pandas as pd
import tqdm
import os
import numpy as np

# from google.colab import drive
# drive.mount('/content/gdrive/')

In [2]:
# data = pd.read_csv("/content/gdrive/My Drive/Colab Notebooks/hwayo.csv", encoding='utf-8')
data = pd.read_csv("hwayo.csv", encoding='utf-8')


data = data.drop(data.columns[[0,1,4,5,6,7,8,9,10,12,13,14,16,18,19]], axis='columns')

data = data.drop([0,1],0)

data.columns=['product','volume','quantity','price','locate'] #거래일, 거래처, 물품, 수량, 가격, 출고지명

data = data.reset_index()

data = data.drop(data.columns[[0]], axis='columns')

data = data.drop(len(data)-1)

data = data.fillna(value='0')

data = data[data.locate != '기타']

data = data.reset_index()

data = data.drop(data.columns[[0]], axis='columns')

data['volume'] = pd.to_numeric(data['volume'])



for i in tqdm.trange(len(data)):
  data['price'][i] = int(data['price'][i].replace(",",""))
  data['quantity'][i] = int(data['quantity'][i].replace(",",""))


# 직영점 기타, 기타는 제거

  0%|          | 0/3235 [00:00<?, ?it/s]/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
100%|██████████| 3235/3235 [00:00<00:00, 4694.97it/s]

In [0]:
# table = pd.read_csv("/content/gdrive/My Drive/Colab Notebooks/table.csv", encoding='utf-8')
table = pd.read_csv("table.csv", encoding='utf-8')
table.rename(columns = {'Unnamed: 0' : 'alcohol', 'Unnamed: 1' : 'volume'}, inplace = True)
# product_list = pd.read_csv("/content/gdrive/My Drive/Colab Notebooks/product_list.csv", encoding='utf-8')
product_list = pd.read_csv("product_list.csv", encoding='utf-8')

In [4]:
for i in range(0,len(data)):
  if data['locate'][i] == '직영점':
    locate1 = ' 기타1 '
    locate2 = ' 기타2 '
  elif data['locate'][i] == '업소':
    locate1 = ' 업소1 '
    locate2 = ' 업소2 '
  elif data['locate'][i] == '계열사':
    locate1 = ' 기타1 '
    locate2 = ' 기타1 '
  elif data['locate'][i] == '소매점':
    locate1 = ' 소매1 '
    locate2 = ' 소매2 '
  elif data['locate'][i] == '면세':
    locate1 = ' 면세1 '
    locate2 = ' 면세2 '
  elif data['locate'][i] == '수출':
    locate1 = ' 수출1 '
    locate2 = ' 수출2 '
  elif data['locate'][i] == '영남팀':
    locate1 = ' 영남팀1 '
    locate2 = ' 영남팀2 '
  elif data['locate'][i] == '유통':
    locate1 = ' 유통1 '
    locate2 = ' 유통2 '
  volume = int(data['volume'][i])
  price = int(data['price'][i])
  quantity = int(data['quantity'][i])
  for j in range(0,len(product_list)):
    if data['product'][i] == product_list['product'][j]:
      alcohol = product_list['alcohol'][j]
      for k in range(0, len(table)):
        if alcohol == 1 or alcohol == 2 or alcohol == 3 or alcohol == 4 or alcohol == 5:
          if table['alcohol'][k] == alcohol:
            table[locate1][k] += quantity
            table[locate2][k] += price
        else:
          if table['alcohol'][k] == alcohol:
            if str(volume) == table['volume'][k]:
              table[locate1][k] += quantity
              table[locate2][k] += price

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [0]:
# table.to_csv("/content/gdrive/My Drive/Colab Notebooks/result.csv", header=True, index=False, encoding='cp949')
table.to_csv("result.csv", header=True, index=False, encoding='cp949')

In [6]:
table

    alcohol volume   유통1        유통2   ...   군납1    군납2     기타1       기타2
0        41    750    330   10164000  ...      0      0      20    616000
1        41    500    240    5148000  ...      0      0     196   4204200
2        41    375   2868   48583920  ...      0      0      84   1422960
3        41    200     72     657360  ...      0      0       0         0
4        41     소계      0          0  ...      0      0       0         0
5        25    750   2040   32089200  ...      0      0    1083  17035590
6        25    500   2514   27100920  ...      0      0     292   3147760
7        25    375  17202  159039540  ...      0      0    1143  13743950
8        25    200  14646   66398160  ...      0      0      50    800000
9        25     소계      0          0  ...      0      0       0         0
10       23   1800      0          0  ...      0      0       0         0
11       23    750      0          0  ...      0      0       0         0
12       23    375      0          0  ...      0      0       0         0
13       23     소계      0          0  ...      0      0       0         0
14       17    750    300    4059000  ...      0      0      60    811800
15       17    375   4062   28149660  ...      0      0     106    734580
16       17    200   3120   12792028  ...      0      0      24     98400
17       17     소계      0          0  ...      0      0       0         0
18       53    750     20    1100000  ...      0      0      40   2200000
19       53    500    402   14713200  ...      0      0      88   3220800
20       53    200      0          0  ...      0      0       0         0
21       53     소계      0          0  ...      0      0       0         0
22        1      0    135   14795995  ...      0      0     146  16001600
23        2      0      0          0  ...      0      0      12    562800
24        3      0     60    1485000  ...      0      0      12    297000
25        4      0      0          0  ...      0      0  734991   2457000
26        5      0    101    4355120  ...      0      0     168   7244160

[27 rows x 18 columns]

In [0]:

# 

# 

# 


# data['buyer_code'] = pd.to_numeric(data['buyer_code'])

# code_index = data[data['buyer_code'] > 90000].index

# data = data.drop(index = code_index)

# data = data.reset_index()

# data = data.drop(data.columns[[0]], axis='columns')

# for _ in tqdm.trange(len(data['date'])):
#     data['date'][_] = str(data['date'][_].replace("-",""))
#     data['quantity'][_] = int(data['quantity'][_].replace(",",""))
#     data['price'][_] = int(data['price'][_].replace(",",""))
#     data['buyer_code'][_] = int(data['buyer_code'][_])


# original2 = data #전처리 후 저장

# original2.to_csv("/content/gdrive/My Drive/Colab Notebooks/delete/pre-data.csv", header=True, index=False, encoding='cp949')